name: flutter_icons
description: Customizable Icons for Flutterï¼Œyou can use with over 3K+ icons in your flutter project. Forked from https://github.com/flutter-studio/flutter-icons.git
version: 1.3.2
homepage: https://github.com/f10smobileteam/flutter-icons.git

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AntDesign
      fonts:
        - asset: fonts/AntDesign.ttf
    - family: Entypo
      fonts:
        - asset: fonts/Entypo.ttf
    - family: EvilIcons
      fonts:
        - asset: fonts/EvilIcons.ttf
    - family: Feather
      fonts:
        - asset: fonts/Feather.ttf
    - family: FontAwesome
      fonts:
        - asset: fonts/FontAwesome.ttf
    - family: FontAwesome5_Brands
      fonts:
        - asset: fonts/FontAwesome5_Brands.ttf
    - family: FontAwesome5
      fonts:
        - asset: fonts/FontAwesome5_Regular.ttf
    - family: FontAwesome5_Solid
      fonts:
        - asset: fonts/FontAwesome5_Solid.ttf
    - family: Foundation
      fonts:
        - asset: fonts/Foundation.ttf
    - family: Ionicons
      fonts:
        - asset: fonts/Ionicons.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: fonts/MaterialCommunityIcons.ttf
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons.ttf
    - family: Octicons
      fonts:
        - asset: fonts/Octicons.ttf
    - family: SimpleLineIcons
      fonts:
        - asset: fonts/SimpleLineIcons.ttf
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons.ttf
    - family: Zocial
      fonts:
        - asset: fonts/Zocial.ttf

  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.